name: "Check pull request"
on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/filters-pr-checker@v1.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          imgur_client_id: ${{ secrets.IMGUR_CLIENT_ID }}
